### PR TITLE
Zooming to ESC on load no longer crashes

### LINKED ISSUE #35: Loading the map with a zoomed ESC selected fails to initialise TomSelect
Repro steps:

1. Load the map as normal, and zoom to an ESC
2. Either click refresh or copy-paste the URL (e.g. http://localhost:2023/?districts=esc&zoomto=20&year=2023 - I found this while investigatign #34)
3. The dropdowns for zooming to districts don't initialise properly, and the console reports `Uncaught TypeError: document.getElementById(...).tomselect is undefined`

I suspect there's a timing issue here, whereby the zoom to district functionality is trying to run before the dropdown is populated, and then trying to look up a value from the dropdown.  It's odd that it seems to only affect ESDs, not school districts, though.

### PR DESCRIPTION
**Pull request by eldang**
Resolves #35 

The issue was that when zooming to an ESC, the code always tries to reset the ISDs dropdown.  But when zooming _on page load_, it was trying to reset that dropdown's tom-select before the tom-select had even been created.  So I've simply added a check that the tom-select exists, and if it doesn't exist then the function doesn't try resetting it.

### CODE REVIEW

File: scripts/functions.js [hunk 1]
```diff
@@ -503,7 +503,9 @@ function zoomToPolygon(sourceID, coords, filterField, maskLayer = true) {
 		// reset dropdowns as appropriate
 		if (sourceID !== "state-school-districts") {
 			showSchoolDistricts = false;
-			document.getElementById("school-districts-control").tomselect.clear(true);
+			if (document.getElementById("school-districts-control").tomselect) {
```
Comment (nein09) [inline scripts/functions.js:506]: This is tiny, but I suggest assigning `document.getElementById("school-districts-control")` to a variable for the if statement and then using it on line 507 if needed because DOM queries are actually kind of expensive (although an ID query is the cheapest kind)

**Comment by nein09** [comment]
Thank you for this! What an annoying bug.

File: scripts/functions.js (hunk 1 above)
Comment (eldang) [reply scripts/functions.js]: Oh, interesting.  I don't have a good sense of the cost of operations like that, I think mainly because I'm used to map operations always being a bigger term.  But it seems like a good habit to be in so I've made the change, and found a few other `document.getElementById()` calls to de-duplicate - some of which won't affect performance at all because they're in different branches of a conditional, but that'll be better for future code maintenance.

Comment (nein09) [reply scripts/functions.js]: whoa, nice!

**Review by nein09 — APPROVED** [review]

**Comment by coregis** [comment]
LGTM! Thank you @eldang Eldan for fixing the bug and thank you @nein09 Melinda for your suggestions to improve performance
